- Dockerfile
Add postgresql repository to get the latest version of postgresql-client
> Add postgresql repository

- common.yaml
- devel.yaml
- prod.yaml
- setup-devel.yaml
- test.yaml
Reverts Tecnativa/docker-odoo-base#45
> Revert "[DCK][FIX] Adapt to last changes in configuration generation"

- Dockerfile
Reverts Tecnativa/docker-odoo-base#44
> Revert "Fix configuration generation at entrypoint"

- Dockerfile
- tests/__init__.py
* Create ssh directory
* Create private addons directory
> [FIX] Create directories that are expected to exist

- .travis.yml
- entrypoint.d/40-addons-link
- tests/__init__.py
- tests/scaffoldings/dotd/auto/addons/dummy_addon
- tests/scaffoldings/dotd/docker-compose.yaml
- tests/scaffoldings/smallest/docker-compose.yaml
Also die if addons linking process fails for some reason.
> [FIX] Remove pre-existing wrong symlinks

- README.md
- bin/autoupdate
- tests/__init__.py
> Add autoupdate utility

- Dockerfile
- README.md
- lib/odoobaselib/installer.py
- tests/__init__.py
- tests/scaffoldings/dotd/custom/dependencies/pip.txt
It also fixes #65 BTW. Tests included.
> Add --upgrade to pip install

- lib/odoobaselib/installer.py
> Skip apt update if no apt packages are to be installed

- bin/direxec
This should help diagnose #79.
> Add logging to direxec script

- 11.0.Dockerfile
- 8.0.Dockerfile
> Avoid text file busy after running onbuild.d

- .travis.yml
- hooks/build
- lib/odoobaselib/__init__.py
- tests/__init__.py
- tests/scaffoldings/dotd/custom/dependencies/apt_build.txt
- tests/scaffoldings/dotd/custom/dependencies/pip.txt
- tests/scaffoldings/dotd/custom/src/addons.yaml
#84 introduced a regression that violated [the addon priority table](https://github.com/Tecnativa/docker-odoo-base#optodoocustomsrcaddonsyaml). This fixes the regression and tests it.
> 🚑 Fix odoo core addon taking priority over extra version

- lib/odoobaselib/__init__.py
@Yajo fix for  https://github.com/Tecnativa/docker-odoo-base/issues/91
> Registering only valid Odoo modules from custom dir

- README.md
Document new features from #117, fixes #98.
WIP until:
> Document network isolation

- bin/addons
- lib/odoobaselib/__init__.py
- tests/__init__.py
- tests/scaffoldings/dotd/custom/src/addons.yaml
Allows us to check if addon definitions match found addons.
> Addons explicit mode

- bin/addons
- tests/__init__.py
This will allow excluding addons that i.e. need internet access from QA builds that run within an internal network.
> Allow to include or exclude addons

- common.yaml
- setup-devel.yaml
See https://github.com/Tecnativa/docker-odoo-base/pull/132 and https://github.com/odoo/odoo/pull/23870#issuecomment-378586668.
> [DCK] Use PYTHONOPTIMIZE=1 by default

- .env
- common.yaml
Solves issue https://github.com/Tecnativa/docker-odoo-base/issues/137 together with https://github.com/Tecnativa/docker-odoo-base/pull/138
> add DBFILTER to common environment

- .env
- prod.yaml
https://github.com/containous/traefik/issues/1380 was fixed, it's time to support it.
> [DCK] Add alternative domain redirection

- lib/odoobaselib/__init__.py
Before this patch, you built, got a missing addon, removed, built again, and the loop repeated many times.
Now, you get at once all the failures.
> Output failing addons once for all loop

- lib/odoobaselib/__init__.py
> Add doodba logger handler and formatter

- lib/doodbalib/__init__.py
Before this patch, when addons.yaml was not defining private or odoo/addons keys, all contents there were being included.
If anybody put there a text file, it was getting included also, so this patch fixes #179.
Now, those are processed in equal conditions as the rest of repo-addon definitions.
BTW I'm removing the deprecated `filtered` parameter, which wasn't being used since we deprecated the addon linking at build long ago in #27.
> Expand default addons.yaml sections like the rest

- 11.0.Dockerfile
- 12.0.Dockerfile
- 8.0.Dockerfile
- bin/install.sh
- tests/__init__.py
> Include watchdog in odoo v9+

- tests/__init__.py
Fix https://github.com/Tecnativa/doodba/issues/170.
> Remove test workarounds for v12

- 13.0.Dockerfile
- tests/__init__.py
> Include ssh client in v13

- README.md
- bin/autoaggregate
- lib/doodbalib/__init__.py
- tests/__init__.py
- tests/scaffoldings/addons_env/Dockerfile
- tests/scaffoldings/addons_env/custom/src/addons.yaml
- tests/scaffoldings/addons_env/docker-compose.yaml
> add new ENV node in addons.yaml

- .prettierrc.yml
- README.md
This helps keeping a more consistent README code.
Includes the change and it execution.
> Make prettier wrap prose

- 11.0.Dockerfile
- 12.0.Dockerfile
- 13.0.Dockerfile
- 8.0.Dockerfile
- tests/__init__.py
- tests/scaffoldings/addons_env/custom/src/addons.yaml
This is a requirement to be able to use click-odoo-makepot
@Tecnativa TT23467
> Make msgmerge CLI tool available

- 11.0.Dockerfile
- 12.0.Dockerfile
- 13.0.Dockerfile
- README.md
Addresses #308.
I wasn't really sure how much documentation to add. I tried to keep it short on purpose :)
> Add inotify support

- .github/workflows/ci.yaml
- .isort.cfg
- 14.0.Dockerfile
- README.md
- bin/direxec
- tests/__init__.py
- tests/scaffoldings/dependencies/custom/build.d/150-conditional-ruby
- tests/scaffoldings/dependencies/custom/src/addons.yaml
- tests/scaffoldings/settings/custom/scripts/test_settings.py
- tests/scaffoldings/settings/custom/scripts/test_settings_python_odoo_shell.py
Continuation of #323 (I don't know why it got closed :roll_eyes:)
- Make it `:latest`.
- Fix the common prerelease-failing tests.
- Fix some tests that were testing deprecated features in versions where those were no longer available.
- Remove ptvsd and use only debugpy (will work only after #324 is merged).
TT22772
> Add Odoo 14.0

- bin/preparedb
- tests/__init__.py
- tests/scaffoldings/settings/custom/scripts/test_ir_config_parameters.py
Prepopulates DB with helpful simple data
Add tests
TT27635
> Add preparedb script

- 11.0.Dockerfile
- 12.0.Dockerfile
- 13.0.Dockerfile
Follow up of 02283864c451d087de40676751eeda78cebdc926
ping @Yajo
> Pin pg_activity version to avoid psycopg2 problems

- 14.0.Dockerfile
Made optional after https://github.com/odoo/odoo/commit/6fa4dbf2047f5e531257876c14a419da67df3f79
> Add pdfminer.six

- 12.0.Dockerfile
- 13.0.Dockerfile
- 14.0.Dockerfile
Improves Odoo mime type detection out of the box.
See https://github.com/odoo/odoo/blob/2dfa8fd0022b0a1fc97b721b3b8c3dd4f28889b3/odoo/tools/mimetypes.py#L164-L173 and the full story from https://github.com/OCA/dms/pull/131.
@Tecnativa TT31461
> Add python-magic

- .github/workflows/ci.yaml
- tests/__init__.py
> Update CI to use Postgres 14

- .github/workflows/ci.yaml
- .vscode/settings.json
- 16.0.Dockerfile
- README.md
- tests/__init__.py
- Dockerfile copied from 15.0 and slightly adapted
- Fix tests
- Make it `:latest`.
TODO: Switch to Python 3.10
@Tecnativa TT39845
> Add Odoo 16.0

- .github/workflows/ci.yaml
- tests/__init__.py
- tests/scaffoldings/dependencies/custom/dependencies/200-pip-without-ext
- tests/scaffoldings/dotd/custom/dependencies/pip.txt
> Add 17.0 (continuation)

- 16.0.Dockerfile
- 17.0.Dockerfile
> [FIX] Use newer flanker from source for 16.0 and 17.0

- 16.0.Dockerfile
- 17.0.Dockerfile
Putting this notation, it installs the required dependencies.
Thanks to @yajo for the tip.
@Tecnativa
> [IMP] Use pip notation for flanker deps

- 16.0.Dockerfile
- 17.0.Dockerfile
CC @Tecnativa TT46155
This PR solves the issue https://github.com/Tecnativa/doodba/issues/589
> [FIX] Change version wkhtmltopdf 0.13 to 0.12.6.1 to avoid printig problems

- tests/__init__.py
- tests/scaffoldings/test_artifacts/Dockerfile
- tests/scaffoldings/test_artifacts/docker-compose.yaml
and verify artifacts are stored
[as discussed](https://github.com/Tecnativa/doodba/pull/599#issuecomment-1970619224) with @chienandalu we should add a test to ensure chrome is working as expected in doodba for http test cases
This is failing for 17.0 (showing that the test is detecting missing artifacts) and should start getting passes once https://github.com/odoo/odoo/pull/156738 lands in 17.0.
Info @wt-io-it
> [IMP] tests: add test for screencast

- 17.0.Dockerfile
This will still escape the \n to newline
closes #607
> remove -e from echo inside Dockerfile

- .github/workflows/ci.yaml
- tests/__init__.py
> Add 18.0 (continuation)

- 11.0.Dockerfile
- 12.0.Dockerfile
- 13.0.Dockerfile
- 14.0.Dockerfile
- 15.0.Dockerfile
- 16.0.Dockerfile
- 17.0.Dockerfile
- 18.0.Dockerfile
- conf.d/60-geoip-ge17.conf
- conf.d/60-geoip-lt17.conf
> [ADD] GeoIP version handling to avoid warnings

- .github/workflows/ci.yaml
Build but not push when PR is from a fork
> [IMP] Build but not push when PR is from a fork

- bin/addons
This is useful on doodba-qa :smile:
> [IMP] addons: Allow to enforce modules on dependencies

- .github/workflows/ci.yaml
Set ubuntu 24.04 on test environment
> [FIX] Set ubuntu 24.04 on test environment

- build.d/700-odoo-install
Based on https://github.com/OCA/oca-ci/pull/93
> [FIX] Pip packages installation
