Tecnativa/doodba

bin/autoaggregate, lib/odoobaselib.py
* Fix file extension and references to YML
While technically `.yaml` is a valid file extension for YAML, the commonly used one is `.yml` - especially in Docker realm. This proposes that change.
I also made acsone/git-aggregator#14, although technically that just allows it into auto-complete in the shell. You could already use any file format AFAIK.
I will submit another change to your scaffold too once this is accepted.
=> [FIX] YAML to YML

Dockerfile, README.md, build.d/30-addons-link, build.d/40-clean, entrypoint.d/40-addons-link, lib/odoobaselib.py
This adds a wildcard for the symlinking of modules directories in the `addons.yaml` file, which works out really great for dev instances IMO (or for lazy people, like me).
I tested manually, but didn't really see an obvious way to test via CI. Am I missing something, perhaps?
=> [IMP] Create an addons wildcard

Dockerfile
I propose changing the Odoo user's shell to `/bin/false`. Relevant conversation - https://github.com/Tecnativa/docker-odoo-base/commit/3256bc955b50cf277142dd76e633bdca7fcb96e1#commitcomment-22638986
If the quick `su` access is required, maybe we could use a bash alias in the root user?
=> [IMP] Change Odoo user shell to `/bin/false`

common.yaml, devel.yaml, prod.yaml, setup-devel.yaml, test.yaml
It is now generated in the entrypoint, so some environment variables and arguments need to be swapped.
Adapts to new changes in #38 and #44.
=> [DCK][FIX] Adapt to last changes in configuration generation

Dockerfile
Move build args to env variables, because build args are not available at run time.
This fixes what #38 broke
=> Fix configuration generation at entrypoint

Dockerfile, bin/config-generate, build.d/60-config-generate, entrypoint.d/50-config-generate, tests/scaffoldings/dotd/docker-compose.yaml
Turns out I never made any of the requested changes to remove the backwards compatibility in my forked image (hooray Git and laziness!). Resubmitting #37 in its original form, which is backwards compatible.
I'll still need to add a test for generating it on entrypoint. Should I just choose one of the scaffolds randomly, or do you have some sort of pattern you're going for with them in terms of what they test?
Fix #37
=> [IMP] Move config generation to entrypoint

.env, common.yaml, devel.yaml, prod.yaml, test.yaml
- Use tecnativa/duplicity:postgres-s3 backup image by default.
- Use new entrypoint configuration generation system from #60.
- Fix #63.
=> Update backup and config generation systems

Dockerfile, tests/scaffoldings/dotd/custom/entrypoint.d/pip-install-user
This makes binaries installed by `pip install --user` become directly usable and fixes #76.
=> Add ~/.local/bin to $PATH

11.0.Dockerfile, README.md, bin/addons, build.d/400-clean, lib/odoobaselib/__init__.py, tests/__init__.py
It turns out for linters you possibly need full path of addon.
Current CLI was not very sane, changing it since it's a young feature that I don't expect to be used widely out there.
=> Change addons-install for a better CLI experience

common.yaml, devel.yaml, prod.yaml, test.yaml
This is a **breaking change**.
The purpose of this feature was that you were able to quickly switch branches in the project by using git, and avoid different branches to share the same volumes, since that can lead to errors in different Odoo versions.
At the end of the day, it turns out that feature was not used. Most version switching happens in devel, where you'd have to re-run `setup-devel` stuff, which slowed down the devel process too much.
Other version switches happened when running OpenUpgrade among versions, and in these cases we need to share the same volume among versions, so this "feature" was becoming a "bug".
So, finally we decided to drop it. This eases the initial scaffolding setup (less things to change). If we need different versions, it's as easy as having different …
=> [DCK] No volume versions

8.0.Dockerfile
It seems phantomjs > 2.1.15 does not install in Debian 8 anymore.
This should fix builds for tags 8.0, 9.0 and 10.0.
=> Fix build by pinning PhantomJS version

bin/autoupdate
* `bin/autoupdate` requires that `module_auto_update` is installed in Odoo. Add a comment to remind us.
=> [IMP] Add note about `autoupdate` module requirements

common.yaml, devel.yaml, test.yaml
Use mailhog as smtp catcher for dev environment
- fix #101 
WIP until:
**howto**: when docker-compose -f devel.yaml up, go to http://localhost:8025 to have mailhog.
=> [NEW] convert smtpfake to mailhog catcher

.env, common.yaml, devel.yaml, prod.yaml, setup-devel.yaml, test.yaml
The inbox proxies were a trick to isolate POP3/IMAP (or any other TCP) connections when a database got restored into a non-production environment.
Since Docker 1.10, internal networks are natively supported, which means that any in/out communication outside the container stack gets automatically blocked.
From now on, you can just configure incoming mail as usual in your Odoo instances with the safety that those incoming mails will not be read outside the production environment.
If you still need outside world communication for devel or test environments, you can enable it by switching the internal boolean, or by adding a public network with public access and attaching it to the containers that need it (usually just Odoo).
Note that for this to have a real effect, the `inverseproxy_shared` …
=> [DCK] Remove inbox containers, use internal networks

bin/addons, tests/__init__.py
Comma-separated lists grow too much quickly
This breaks API from #123, but since it was merged minutes ago, I think nobody will care.
=> Multiple with and without calls instead of comma-separating

build.d/200-dependencies, lib/odoobaselib/installer.py, tests/__init__.py, tests/scaffoldings/dependencies/10.0.Dockerfile, tests/scaffoldings/dependencies/11.0.Dockerfile, tests/scaffoldings/dependencies/8.0.Dockerfile, tests/scaffoldings/dependencies/9.0.Dockerfile, tests/scaffoldings/dependencies/custom/dependencies/070-apt-bc.txt, tests/scaffoldings/dependencies/custom/dependencies/150-npm-aloha_world-install.txt, tests/scaffoldings/dependencies/custom/dependencies/200-pip-without-ext, tests/scaffoldings/dependencies/custom/dependencies/270-gem.txt, tests/scaffoldings/dependencies/custom/dependencies/apt-without-sequence.txt, tests/scaffoldings/dependencies/custom/dependencies/apt_build.txt, tests/scaffoldings/dependencies/custom/src/repos.yaml, tests/scaffoldings/dependencies/docker-compose.yaml
Use `OrderedDict` instead of `dict` to ensure the same installation priority between builds (apt > gem > npm > pip) in [build.d/200-dependencies](/Tecnativa/docker-odoo-base/blob/master/build.d/200-dependencies).
This change also ensures that `pip install` dependencies' can be installed through Debian's `apt` (e.g.: `lxml` -> `libxml2-dev libxslt1-dev`).
=> [IMP] Ensure dependencies installation replicability.

devel.yaml
To fix #120:
- Add a new "public" network, which has no restriction
- Bind wdb and smtp containers to that network, since they have no data leakage possibility
- Add a new odoo_proxy service: just a blind netcat that allows external connections to odoo
- Odoo and db are still isolated and cannot access the public network, so the isolation features remain untouched.
=> Proxy for Odoo in devel

bin/install.sh
The current `psycopg2` version (`2.7.4` as of today) shows a **UserWarning** about future packaging changes. Force the version found in the `requirements.txt` from **OCA/OCB**.
This also ensures that the package `psycopg2` won't be reinstalled when enabling `AUTO_REQUIREMENTS` if the `requirements.txt` is synced with the **OCB**'s one.
The log in question is:
> /usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
""")
=> [FIX] Freeze psycopg2 library

test.yaml
[These apis are used by upstream Odoo](https://github.com/odoo/odoo/blob/cd48a806ac636806130efcf5c055f73758cb0902/addons/theme_bootswatch/static/src/less/united/bootswatch.less#L5) and not having them can result in wrongly printed reports or timeouts in website tests when running behind an internal network.
Besides, it serves as a good whitelisting-with-dns-pre-resolving example.
=> [DCK] Whitelist google fonts in test environment

bin/autoupdate
This should keep backwards compatibility wherever needed, while working with the newest features introduced in https://github.com/OCA/server-tools/pull/1190 wherever available. Deprecated features get autodisabled.
=> New update mechanism landed in module_auto_update

11.0.Dockerfile, 8.0.Dockerfile, README.md, bin/direxec, tests/__init__.py, tests/scaffoldings/settings/docker-compose.yaml
Lets automated deployments of new databases with only one language that is not en_US.
=> Support $INITIAL_LANG

11.0.Dockerfile, 8.0.Dockerfile
This should remove some warnings from builds like these:
```
WARN engine less@3.0.2: wanted: {"node":">=4"} (current: {"node":"0.10.29","npm":"1.4.21"}) 
```
Also I hope it adds a workaround for one problem found, related to https://github.com/odoo/odoo/pull/24246, which rendered a useless website with:
The "--no-js" argument is deprecated, as inline JavaScript is disabled by default. Use "--js" to enable inline JavaScript (not recommended).
/usr/local/lib/node_modules/less/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
FileError: optional dependency 'request' required to import over http(s)
in - on line 342, column 1:
341 // General styles
342 @import url(//fonts.googleapis.com/css?family=Open+Sans:400,400italic);
343
=> Upgrade to Node 6.x (LTS) and Less 2.x in all versions

devel.yaml, test.yaml
The file `res_partner_demo.yml` from Odoo base addon was extremely slow to load due to trying to connect to Gravatar. This should speed up all CI builds significatively.
Also include all service proxies from test.yaml into devel.yaml, to speed up reporting at devel time.
@lreficent, this should be fixing the problems you commented to me privately, right?
=> [DCK] Add gravatar proxy

tests/__init__.py
See https://github.com/Tecnativa/docker-odoo-base/issues/67#issuecomment-383051415 for details.
Tests using v10 main scaffolding were testing old image alnog with new one.
=> Main scaffolding is now 11.0

11.0.Dockerfile, 8.0.Dockerfile, tests/__init__.py
We find ourselves to be installing this quite often to track performance and concurrency issues, so it's better to bundle it.
=> Include pg_activity in base image

11.0.Dockerfile, 8.0.Dockerfile
This release fixes the infamous bug https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2711, and according to https://github.com/odoo/odoo/issues/21255#issuecomment-395358801 it should be mostly safe to upgrade from current 0.12.4 version.
=> Upgrade to wkhtmltox 0.12.5

11.0.Dockerfile
Versions 8-10 use postgres client libraries in version 10.x, but version 11 uses 9.x.
Since there's more backwards compatibility than forward, I'm upgrading libs in v11 image here too.
=> Use latest Postgres in v11 image

bin/addons, lib/odoobaselib/__init__.py
Now the error message will be pretty-printed when using `addons` script.
=> Provide better message on failed addons

.env, common.yaml
This makes the `docker-compose push` command to work, and allows those of us using private registries to build only in CI and pull only in prod.
=> [DCK] Add image to odoo service

bin/addons, bin/direxec, bin/log, build.d/200-dependencies, build.d/400-clean, entrypoint.d/40-addons-link, lib/odoobaselib/__init__.py, lib/odoobaselib/installer.py
This avoids polluting the root logger, which could be used for other things.
=> Unified logger

README.md
This change affects documentation only. To apply in your real world deployments:
- Merge https://github.com/Tecnativa/doodba-scaffolding/pull/5 in your downstream scaffolding clone.
- Follow instructions added to README here.
=> Document usage of global whitelist

bin/install.sh
This PR adds a few missing dependencies for Odoo 8.0 instances. They're needed to generate the  **Workflow report** and enable document indexing with `document`.
=> Add missing Odoo 8.0 dependencies

11.0.Dockerfile, 8.0.Dockerfile, README.md, bin/direxec
Without this patch, we were stick in an old ptvsd version, because it was the only one that was actually working, as explained in https://github.com/Microsoft/vscode-python/issues/133#issuecomment-353757512.
However, today it's the contrary: version 3.0.0 is no longer supported by Visual Studio Code, so we need to update it.
The new version has a different CLI, so it's adapted here too (BTW it was broken before too).
Usage instructions updated too.
=> Make ptvsd great again

12.0.Dockerfile, tests/__init__.py, tests/scaffoldings/dependencies/custom/dependencies/apt_build.txt, tests/scaffoldings/dotd/custom/dependencies/apt_build.txt
- Branch 12.0 of OCB has been released, so use it now.
- Enable some tests that should work now. There are still anothers that are disabled.
- Use Python 3.7, now that it has been discovered [it is officially supported][1] ~~and [is going to be tested in OCA repos][2]~~.
[1]: https://twitter.com/__yajo/status/1045228965928062977
[2]: https://twitter.com/moylop260/status/1045230320403062784
=> Use OCB 12.0

12.0.Dockerfile
This is a soft dependency required to perform browser tests.
Temporary workaround for https://github.com/odoo/odoo/pull/27507, to be reverted when merged.
=> Add websocket-client to v12

bin/addons, tests/__init__.py, tests/scaffoldings/dotd/custom/src/dummy_repo/dummy_addon/__manifest__.py, tests/scaffoldings/dotd/custom/src/private/private_addon/__openerp__.py
This tool is required to be able to apply the same testing workflow as found in OCA, namely:
1. Install dependencies of chosen addons.
2. Test & install chosen addons.
See https://github.com/OCA/server-ux/pull/32 and https://github.com/odoo/odoo/pull/27883 to understand the motivation behind this. Take a :coffee: first :stuck_out_tongue_winking_eye:.
=> Allow to find dependant addons only

11.0.Dockerfile, 12.0.Dockerfile, 8.0.Dockerfile
Current fonts shipped by Debian do not render fine in Adobe PDF on Windows and Mac OS.
Most users will use those OS & PDF reader combination, and [Odoo demos and runbots use MS fonts][1].
So, in the hope of providing an opinionated sane default that makes most users happy, we are going to ship Liberation fonts by default, which are an open source alternative to MS fonts that, according to tests, render just fine everywhere.
If anybody wants a more corporative font, they should use it in their reports and install it from apt with provided tools.
[1]: https://github.com/odoo/odoo/issues/27487#issuecomment-431847389
=> Change default fonts to liberation

lib/doodbalib/__init__.py, tests/__init__.py
Since #182, the `addons-install` script in doodba-qa, in projects without private addons, yielded this error:
Addons not found:
{'/opt/odoo/custom/src/private/*'}
This should never be an error, as projects without private addons are not only supported but actually encouraged!
So, I add here this specific exception.
=> Fix error on Doodba QA when private folder is empty

build.d/400-clean, lib/doodbalib/__init__.py
This option was wrongly removed in 7ab4d1f680c5d4f0ca7e9254074c5e6a94e0a3ad, so I'm reverting that change.
We need to know the total addons used, to avoid cleaning them on image build.
=> Restore ability to unfilter addons

8.0.Dockerfile
This package comes from Debian 9, but it is needed because only Liberation 2.x fonts support "ZERO WIDTH NO-BREAK SPACE (U+FEFF)" character, used by Odoo from https://github.com/odoo/odoo/commit/cb2a3afa7e010d1cd7a01c64f5c3ac58b6fd76d2 onwards.
For instance, on Odoo 10 under Doodba, before this patch (and after having merged #181), printing the general ledger report with demo data resulted in this:
This is after the patch:
=> Install fonts-liberation2 in Debian 8 builds

build.d/400-clean, tests/__init__.py, tests/scaffoldings/dotd/custom/src/dummy_repo/dummy_link
This PR is proposed to fix the issue #189 
As proposed in the mentioned issue, a try/catch has been implemented and successfully tested for my use case, however, it may be that OSError is raised for another reason than because directory is a link and therefore the script would still fail when trying to unlink it...
=> Fix removal of linked directories

qa/insider
I was using the `text=True` argument, only in PY3+, for `subprocess.check_call`, but it turns out that argument only exists in PY3.7+, and this code is executed also by PY2.7 and PY3.5, depending on the Odoo image version.
Instead, I just use now `universal_newlines=True`, which is the backwards-compatible equivalent to `text=True`. We'll change that when that backwards compatibility is removed and/or we only support PY3.7+ (a.k.a. only Odoo 12.0+).
This fixes the red build introduced by #193.
=> Use backwards-compatible universal_newlines argument

12.0.Dockerfile
This is a soft dependency in Odoo 12.0 for addons [`phone_validation`][1] and [`sms`][2].
IMHO it should be included by default. We want all Odoo features built-in out of the box.
[1]: https://github.com/odoo/odoo/blob/8f4b98e67fe49516c0c830524de351db67c58357/addons/phone_validation/tools/phone_validation.py#L14
[2]: https://github.com/odoo/odoo/blob/8f4b98e67fe49516c0c830524de351db67c58357/addons/sms/wizard/send_sms.py#L13
=> Add phonenumbers in 12.0

12.0.Dockerfile
This is the minimal version that is supported.
=> Downgrade Python version to 3.5 in v12

11.0.Dockerfile, 12.0.Dockerfile, 8.0.Dockerfile, README.md, bin/autoupdate, tests/__init__.py
This should let us use click-odoo-update instead of autoupdate, and start moving custom scripts to a broader audience and a better supported odoo scripting framework.
=> Include click-odoo-contrib packages

11.0.Dockerfile, 12.0.Dockerfile, 8.0.Dockerfile
This is a preview feature.
Before https://github.com/Tecnativa/doodba/pull/200, the only way to autoupdate addons was to use [OCA's `module_auto_update` module](https://www.odoo.com/apps/modules/11.0/module_auto_update/). As a preview feature, I'm pre-merging https://github.com/acsone/click-odoo-contrib/pull/38 here in Doodba, to allow trusted parallel upgrades everywhere.
However, this should be considered a beta feature.
This commit should be reverted when the above PR is merged in upstream click-odoo-contrib package.
Closes https://github.com/Tecnativa/doodba/pull/160.
=> Include click-odoo-update with parallel support

11.0.Dockerfile, 12.0.Dockerfile, 8.0.Dockerfile, conf.d/20-database.conf
This should allow us to disable the database manager at will in environments, removing the need to protect those controllers through the external proxy.
=> Allow to set list_db parameter by env variable

README.md, tests/__init__.py
- Document changes from Tecnativa/doodba-scaffolding#24.
- Remove scaffolding tests. Since Tecnativa/doodba-scaffolding#15, the scaffolding has its own tests, and these are very hard to maintain.
=> Document outsourcing of secrets

tests/scaffoldings/dotd/docker-compose.yaml
This will just test that this image that will be introduced in https://github.com/Tecnativa/doodba-scaffolding/pull/26 is a drop-in replacement for most use cases.
=> Use tecnativa/postgres-autoconf in dotd tests

8.0.Dockerfile
Images for Odoo v8-10, based on Debian 8, started to display errors when doing `apt-get update`.
The reason is that [the `jessie-updates` apt repo has been removed from apt mirrors](https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html).
I might consider updating the base OS, but for now IMHO the safest thing to do is to remove that repo.
=> Disable the jessie-updates repo in old images

lib/doodbalib/__init__.py
Last builds were saying about previous call to `yaml.load()`:
/usr/local/lib/python3.5/site-packages/doodbalib/__init__.py:93: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Using the safe loader now.
=> Supress yaml.load security warning

lib/doodbalib/installer.py
It can lead to unexpected or unneeded upgrades, making downstream images bigger and less stable.
If you really need a newer (or older) version of any dependency than the one bundled (the one shipped from Odoo `requirements.txt` file), all you have to do is pin it in the scaffolding's `pip.txt` file.
=> Do not --upgrade when installing pip dependencies

11.0.Dockerfile, 12.0.Dockerfile, 8.0.Dockerfile
Being practical, most of the time you need to install this library from git master.
Since https://github.com/Tecnativa/doodba/pull/213 adding [the corresponding line][1] to the scaffolding didn't actually install the version from master. The pip requirements file doesn't have a way to force updating a dependency when it is already installed from git.
It seems the easiest way to fix the situation is to remove `openupgradelib` from the base image. If you really need it, install it when building your subimage, either from pip or from git, however you want.
[1]: https://github.com/Tecnativa/doodba-scaffolding/blob/55a5e1b3ba65bec8604f3260e361f8b6a1d64b2e/odoo/custom/dependencies/pip.txt#L1
=> Remove openupgradelib

bin/autoaggregate
I'm gettings warnings when running setup-devel:
/usr/local/bin/autoaggregate:87: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
for doc in yaml.load_all(yaml_file):
/usr/local/bin/autoaggregate:95: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
for doc in yaml.load_all(yaml_file):
Looks a lot like #209 
BTW, Thanks ffor a GREAT project!
=> yaml.load security warning

bin/addons
[In Odoo v12, tours do not know the database being used](https://github.com/odoo/odoo/issues/32687).
This is a simple workaround that lets us keep on working in v12 as before, and should be backwards compatible.
The fix is to add `--db-filter "^$PGDATABASE$"` to the command.
This can be rolled back when fixed upstream.
=> Filter db when testing addons

12.0.Dockerfile
Odoo v12 supports logging a screencast of failed tours when `ffmpeg` is present and `--logfile` is supplied.
Obviously, including `ffmpeg` here. Screencasts everywhere! 📹
=> Include ffmpeg in v12

11.0.Dockerfile, 12.0.Dockerfile, 8.0.Dockerfile, README.md, tests/__init__.py, tests/scaffoldings/uids_1001/Dockerfile, tests/scaffoldings/uids_1001/custom/src/repos.yaml, tests/scaffoldings/uids_1001/docker-compose.yaml, tests/scaffoldings/uids_default/Dockerfile, tests/scaffoldings/uids_default/custom/src/repos.yaml, tests/scaffoldings/uids_default/docker-compose.yaml
fixes #220 
odoo user is now created in scaffolding build and is created with UID and GID set for build command.
This enables using other uids and gids than 1000 (and no longer uses the others permission group in linux)
makes https://github.com/Tecnativa/doodba/pull/221 obsolete
=> [IMP] enable using other uids than 1000 for odoo user

11.0.Dockerfile, 8.0.Dockerfile, bin/config-generate, conf.d/10-addons.conf, conf.d/20-database.conf, conf.d/30-proxy-mode.conf, conf.d/40-smtp.conf, conf.d/50-demo-data.conf, tests/scaffoldings/settings/custom/conf.d/00-defaults.conf, tests/scaffoldings/settings/custom/conf.d/10-custom.conf, tests/scaffoldings/settings/custom/scripts/test_settings.py
Before Odoo v11, Odoo wasn't so strict when reading configuration. Since v11, where Python 3 started to be used, it used the new default `strict=True` mode to read configuration files.
The strict mode forbids section and option repetitions. Although that seems legit for most apps (even Odoo itself), in Doodba we provide a set of predefined defaults that downstream scaffoldings should be able to override.
To allow such behavior, now the script that generates the final config will do it in `strict=False` mode, but will remove duplicates and just use the latest option defined, effectively producing a strict config file out of a collection of non-strict configs.
Of course, options until now are respected, like output of result while in `LOG_LEVEL=DEBUG` or env variable substitution.
Full …
=> Smarter, less strict, config generator

bin/config-generate
configs should be read in order:
00-something.conf should be parsed before 10-another_thing.conf
fixes https://github.com/Tecnativa/doodba/issues/230
=> [FIX] add configs in sorted order

bin/autoaggregate
This chunk of code was warning:
```
/usr/local/bin/autoaggregate:127: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
has_contents = yaml.load(repos_file)
```
Since it was just a workaround for https://github.com/acsone/git-aggregator/pull/23 and that's fixed already, I can remove it and fix the warning all with one shot.
=> Remove unsafe call

bin-deprecated/install.sh
Recently faced this error just with `odoo --version`:
ERROR: openerp 7.0 requires pychart, which is not installed.
[...]
pkg_resources.DistributionNotFound: The 'pychart' distribution was not found and is required by openerp
@Tecnativa TT18838
=> Add pychart for v7

build.d/700-odoo-install, tests/scaffoldings/uids_1001/docker-compose.yaml
The odoo script must always point to the right executable in whatever odoo version you're using.
That's how it works for test and prod environments, but 89360140728b2e09c97cbd5bb7daae6ff581fbd0 introduced a regression on this matter for devel environment.
The main problem is that it was trying to be "smarter" by checking script existence, while at build time, in devel, those scripts still do not exist, so it always resolved to latest version (which uses `odoo-bin`) and broke older versions (those that use `openerp-server` or `odoo.py`).
I made it dumber-but-working again, and added a little comment to avoid future me to try to "fix" this again.
=> Fix wrong location of odoo script target

bin/autoaggregate, lib/doodbalib/__init__.py
This allows builds to pass `LOG_LEVEL=DEBUG` and somehow workaround https://github.com/acsone/git-aggregator/issues/31 while https://github.com/acsone/git-aggregator/pull/35 is not released yet.
@Tecnativa TT18838
=> Pass doodbalib log level to gitaggregate

11.0.Dockerfile, 12.0.Dockerfile, 13.0.Dockerfile, 8.0.Dockerfile
previously a now deleted branch was used (parse-version was merged in https://github.com/acsone/click-odoo/commit/eb9e5568baead002da877c729b57bd9274d3f4ec)
fixes https://github.com/Tecnativa/doodba/issues/247
=> fix build errors by using merged pull request for click-odoo

11.0.Dockerfile, 12.0.Dockerfile, 13.0.Dockerfile, 8.0.Dockerfile
I currently face up to an issue with current docker image.
My local user is freeipa user (not in /etc/passwd).
The fix is to add an option to useradd.
the -l flag of useradd prevents adding the user to the lastlog and faillog databases. Then no issue with overlay2 and lastlog file.
cf https://www.reddit.com/r/docker/comments/9jy0au/weird_behavior_while_creating_user_in_dockerfile/
=> Add -l option to useradd

lib/doodbalib/__init__.py
With this patch, if a repo has a README file (for example) and it's included as `*`, it will not fail saying that addon is missing.
@Tecnativa TT20969
=> Skip files in external repos

README.md
This is a useful case for Doodba users, where possibly you want to pre-merge a patch done for Odoo v11 into your Odoo v13 deployment, before Odoo approves it.
Using just git branches is not much helpful in this case because no git history is shared, so conflicts would arise always.
In fact, this might be the best way to apply merges *always*. That's to be investigated.
Upstream support for diffs and patches is being tracked in https://github.com/acsone/git-aggregator/issues/34, but in the mean time this option is available today, so it's better to make it more obvious.
@Tecnativa TT19951
=> Document shell_command_after to merge diffs

bin/addons, tests/__init__.py
Before this patch:
- When an addon was included with `--with`, its dependencies were not detected.
- When an addon was excluded with `--without` but it was a dependency of another addon that was included, it ended up in the final list (although explicitly excluded).
TT20969 TT20963
=> Fix dependency inclusion and exclusion detection

bin/addons, lib/doodbalib/__init__.py, tests/__init__.py, tests/scaffoldings/dotd/custom/src/addons.yaml, tests/scaffoldings/dotd/custom/src/enterprise/make_odoo_rich/__openerp__.py
It's common that you want to test enterprise addons in a separate fashion from the rest of addons, same as core, extra or private addons.
To support that, from now on, a repo called `enterprise` will be excluded when you run `addons` with `--extra` flag. Just add `--enterprise` explicitly if you need it.
TT20969
=> Add --enterprise to addons command

README.md
``https`` service doesn't exist anymore. Not sure, though, shall I replace it with ``proxy``
=> make "restart odoo" README section up-to-date

README.md
This breaking change will follow https://github.com/Tecnativa/doodba-scaffolding/pull/56.
@Tecnativa TT20505
=> Document new RELAY_PASSWORD variable

README.md
Without username it says
> psql: FATAL:  role "root" does not exist
And without database:
> psql: FATAL:  database "odoo" does not exist
=> Clarify command to connect via psql

11.0.Dockerfile, 12.0.Dockerfile, 13.0.Dockerfile, 8.0.Dockerfile, tests/__init__.py, tests/scaffoldings/uids_mac_os/Dockerfile, tests/scaffoldings/uids_mac_os/docker-compose.yaml
On macOS the default UID and GID are 501 and 20. The gid 20 conflicts with debians dialout group in doodba. When building on macOS one gets a message like this:
```
groupadd: GID '20' already exists
ERROR: Service 'odoo' failed to build: The command '/bin/sh -c groupadd -g $GID odoo     && useradd -l -md /home/odoo -s /bin/false -u $UID -g $GID odoo     && mkdir -p /var/lib/odoo    && chown -R odoo:odoo /var/lib/odoo /qa/artifacts     && chmod a=rwX /qa/artifacts     && sync' returned a non-zero code: 4
```
We fixed this by allowing the added group odoo having the same gid as any existing group and added a test for building with default macOS ids.
A side effect is that if you check the group name of a directory in the container it will return the primary group name (dialout for 20) not …
=> Master allow duplicate gid

.vscode/settings.json, bin/addons
It turns out that an arguments syntax error exits with 0x2, which is the same exit code I chose to indicate there are no addons. This way, there's no way to know if there was a real error or there were simply no addons found.
So I change the exit code for addons not found to 0x4.
https://github.com/Tecnativa/doodba-qa/pull/17 won't be able to complete without this patch.
TT21246
=> Change no addons found exit code to 4

README.md
Without the step you will get following error:
ERROR: Network inverseproxy_shared declared as external, but could not be found. Please create the network manually using `docker network create inverseproxy_shared` and try again.
=> add missing step for inverseproxy

8.0.Dockerfile
When running Odoo v9 and using:
```
import wdb
wdb.set_trace()
```
wdb tries to import simplejson which is not packaged into the base image for Odoo v9. So wdb was only working if simplejson was added in the scaffolding. Ideally wdb should work out of the box also for Odoo v9.
Stacktrace from when i discovered this issue while trying to get #275
```
odoo_1                    |   File "/opt/odoo/custom/src/odoo/addons/website/models/ir_http.py", line 116, in _dispatch
odoo_1                    |     self._geoip_setup_resolver()
odoo_1                    |   File "/opt/odoo/custom/src/odoo/addons/website/models/ir_http.py", line 75, in _geoip_setup_resolver
odoo_1                    |     import wdb
odoo_1                    |   File "/usr/local/lib/python2.7/dist-packages/wdb/__init__.py", …
```
=> fix: wdb for Odoo v9.0 needs simplejson installed to work

11.0.Dockerfile, 12.0.Dockerfile
Python 3.5 is flawed. It affects Odoo badly as shown in https://github.com/odoo/odoo/issues/20158. Odoo claims to have included a workaround for that in their code, but that simply doesn't work according to real world tests.
The only fix is to update Python version, so here's the update.
This patch reverts #199 for v11 and v12.
@Tecnativa TT21841
=> Update Python 3 version in v11 and v12

README.md
command "addons" doesn't accept modules as positional arguments.
Example:
$ docker-compose run --rm odoo addons init --test web_debranding
doodba INFO: Executing addons init --test web_debranding
usage: addons [-h] [-c] [-d] [-e] [-f] [-i] [-n] [-p] [-s SEPARATOR] [-t] [-x]
[-w WITH_] [-W WITHOUT]
{init,update,list}
addons: error: unrecognized arguments: web_debranding
=> add --with to addons command

11.0.Dockerfile, 12.0.Dockerfile, 13.0.Dockerfile
This reverts commit dbaaa2782a2d00e093063ebee3478c1d4093def3 from https://github.com/Tecnativa/doodba/pull/290.
Also reverts v13 to oldest supported python version (3.6 per the docs).
@Tecnativa TT23435
=> Revert "Update Python 3 version in v11 and v12"

conf.d/00-base.conf
This new v13+ feature helps debugging JS tests. It makes sense to ship a default location for these things. Settings won't hurt on lower versions.
This combines with https://github.com/Tecnativa/doodba-copier-template/pull/68 to become actually useful.
=> Configure screenshots and screencasts dir

11.0.Dockerfile, 8.0.Dockerfile
[Last weekly build][1] failed with:
```
#8 [base 5/18] RUN gem install --no-rdoc --no-ri --no-update-sources bootst...
#8 4.129 ERROR:  Error installing bootstrap-sass:
#8 4.129 	autoprefixer-rails requires Ruby version >= 2.4.
#8 4.147 Successfully installed execjs-2.7.0
#8 ERROR: executor failed running [/bin/sh -c gem install --no-rdoc --no-ri --no-update-sources bootstrap-sass --version '<3.4'     && rm -Rf ~/.gem /var/lib/gems/*/cache/]: runc did not terminate sucessfully
```
[Second to last build][2] passed with:
```
#7 [base 4/16] RUN gem install --no-rdoc --no-ri --no-update-sources bootst...
#7 1.419 Successfully installed execjs-2.7.0
#7 1.419 Successfully installed autoprefixer-rails-9.8.5
#7 1.419 Successfully installed bootstrap-sass-3.3.7
#7 1.419 3 gems installed
#7 DONE …
```
=> Install older autoprefixer-rails dependency

bin/autoaggregate
Recently Python 2 builds (Odoo <= v10) started failing due to https://github.com/acsone/git-aggregator/issues/47.
Here's the fix.
=> Fix autoaggregate in python 2 versions

11.0.Dockerfile, 12.0.Dockerfile, 13.0.Dockerfile, 8.0.Dockerfile, README.md, bin/direxec
Seems like `debugpy` is the recommended library for debugging Python with VSCode, so it makes sense to make this transition.
https://code.visualstudio.com/docs/python/debugging#_debugging-by-attaching-over-a-network-connection 
https://github.com/microsoft/debugpy
This updates the container, but it is still needed to update the template under copier (see https://github.com/Tecnativa/doodba-copier-template/pull/127)
TT25875
=> Update ptvsd -> debugpy

.github/workflows/ci.yaml
> The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> upgrade to to new github api

14.0.Dockerfile
Seems like Odoo is using Python 3.8 for Runbots and Odoo.sh in v14: https://github.com/odoo/runbot/issues/414#issuecomment-710311902
TT26297
=> Update 14.0 Dockerfile to use Python 3.8, as in Odoo.sh and runbots

11.0.Dockerfile, 12.0.Dockerfile, 13.0.Dockerfile, 14.0.Dockerfile, 8.0.Dockerfile
This plugin enables recordset debug collection in Doodba and
is compatible with all IDE's supporting pydevd including VSCode
and pycharm.
=> Add pydevd-odoo plugin

8.0.Dockerfile
Partially reverts https://github.com/Tecnativa/doodba/commit/4fa82ccfb99ddb6f06e745ecfc3d6dccd2add861
Pydevd-odoo introduces Syntax Error for python < 3 https://github.com/trinhanhngoc/pydevd-odoo/blob/master/pydevd_plugins/extensions/pydevd_plugin_odoo.py#L37
This eliminates pydevd-odoo functionality but keeps debugging working
TT26189
=> Remove pydevd-odoo for Odoo <= v10

entrypoint.d/50-config-generate
Instead of only regenerating the `/opt/odoo/auto/odoo.conf` file when none exists, always regenerate it.
TT26597
=> Always regenerate odoo.conf file

14.0.Dockerfile
Pydev-odoo introduces error in Python 3.8 (used in v14): https://github.com/trinhanhngoc/pydevd-odoo/issues/3
Removing until issue is fixed
cc @Tecnativa @Yajo
=> FIX: Temporarily remove pydevd-odoo

.github/workflows/ci.yaml
As explained in several warnings like https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages#about-docker-and-github-packages, GitHub Packages Docker registry will soon be deprecated in favour of GHCR. This is a good chance to migrate to the new registry, and also improve our CI flow in https://github.com/Tecnativa/doodba-copier-template with this images.
ping @Yajo 
I think you will need to add the respective secrets in the project.
@Tecnativa TT26590
=> Migrate from GitHub Packages Docker registry to GitHub Container Registry

.github/workflows/ci.yaml
As done before with build action, now use the `poetry` environment instead of installing everything with `pip`
Fixes https://github.com/Tecnativa/doodba/runs/1576018407 and is a continuation of https://github.com/Tecnativa/doodba/pull/361/commits/b6615c1d88a060d154ed32872945f07cad26b447
=> Fix push action to run on poetry env

11.0.Dockerfile, 12.0.Dockerfile, 13.0.Dockerfile, 14.0.Dockerfile, 8.0.Dockerfile, bin/direxec, build.d/250-postgres-client, tests/__init__.py, tests/scaffoldings/postgres_client_version/Dockerfile, tests/scaffoldings/postgres_client_version/docker-compose.yaml
When using pg_dump in the odoo container we had the problem that we couldn't restore the dumps on our main postgres server because they where using a different pg_dump version than the pg_restore outside of the container.
With this change the version of pg_dump, psql and pg_restore inside of the odoo container can be set by adding the build parameter `DB_VERSION: ${DB_VERSION}` to use the DB_VERSION from .env or `DB_VERSION: 10` to specify a specific version for the odoo containers postgres-client package.
Unfortunately just specifying postgres-client-10 in dependencies/apt.txt did install psql version 10 but did not set as the default psql in the odoo user's path (that was still version 13)
=> image: enable defining postgres client version on build

lib/doodbalib/__init__.py, tests/__init__.py, tests/scaffoldings/addons_env_double/Dockerfile, tests/scaffoldings/addons_env_double/custom/src/addons.yaml, tests/scaffoldings/addons_env_double/custom/src/repos.yaml, tests/scaffoldings/addons_env_double/docker-compose.yaml
Checking for duplicates in `doodbalib` was impeding having the same addon defined more than once in `addons.yaml`, even if it was for different environments.
This moves that check to the entrypoint, to be executed only when symlinking the addons.
Also add tests for that situation
@Tecnativa
TT27711
=> Add option to have multiple addons versions defined in different environments

11.0.Dockerfile, 12.0.Dockerfile, 8.0.Dockerfile
https://bootstrap.pypa.io/ started using python >3.5 syntax for the `get-pip.py` script.
It is, then, necessary to fetch the correct version for each image.
Fixes latest build errors: https://github.com/Tecnativa/doodba/runs/1799238330?check_suite_focus=true#step:7:1000
```bash
#5 49.44 Traceback (most recent call last):
#5 49.44   File "/dev/stdin", line 24244, in <module>
#5 49.44   File "/dev/stdin", line 199, in main
#5 49.44   File "/dev/stdin", line 82, in bootstrap
#5 49.44   File "<frozen importlib._bootstrap>", line 968, in _find_and_load
#5 49.44   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
#5 49.44   File "<frozen importlib._bootstrap>", line 896, in _find_spec
#5 49.44   File "<frozen importlib._bootstrap_external>", line 1171, in find_spec
#5 …
```
=> Fix builds: pip bootstrap

11.0.Dockerfile, 12.0.Dockerfile, 8.0.Dockerfile, tests/__init__.py, tests/scaffoldings/dependencies/custom/dependencies/270-gem.txt, tests/scaffoldings/dotd/custom/build.d/201-assert-dependencies, tests/scaffoldings/dotd/custom/dependencies/gem.txt
During our nightly build the builds for 11.0 and 12.0 failed with the following message:
```
Hi there!
The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:
https://bootstrap.pypa.io/pip/3.5/get-pip.py
Sorry if this change causes any inconvenience for you!
We don't have a good mechanism to make more gradual changes here, and this
renaming is a part of an effort to make it easier to us to update these
scripts, when there's a pip release. It's also essential for improving how we
handle the `get-pip.py` scripts, when pip drops support for a Python minor
version.
There are no more renames/URL changes planned, and we don't expect that a need
would arise to do this again in the near future.
Thanks for …
```
=> [FIX] dependencies: update pip install url and replace yanked aloha_world gem

11.0.Dockerfile, 12.0.Dockerfile, 13.0.Dockerfile, 14.0.Dockerfile
~~It is required for the package setup https://github.com/OCA/pylint-odoo/blob/master/setup.py#L5
But not specified in the requirements, and pip has no control on its insallation. It is done with easy_install, which may cause problems.
See https://pip.pypa.io/en/latest/cli/pip_install/#controlling-setup-requires~~
Install version from OCA/pylint-odoo#329 with a more modern packaging method, avoiding errors with setuptools
=> Fix pylint-odoo and click-odoo installation

11.0.Dockerfile, 12.0.Dockerfile, 13.0.Dockerfile, 14.0.Dockerfile, bin/autoaggregate, build.d/100-repos-aggregate, build.d/800-permissions, tests/__init__.py, tests/scaffoldings/aggregate_permissions/.dockerignore, tests/scaffoldings/aggregate_permissions/.gitignore, tests/scaffoldings/aggregate_permissions/Dockerfile, tests/scaffoldings/aggregate_permissions/docker-compose.yaml, tests/scaffoldings/repo_merge/Dockerfile, tests/scaffoldings/repo_merge/custom/build.d/099-git_merge_no_ff, tests/scaffoldings/repo_merge/custom/src/repos.yaml, tests/scaffoldings/repo_merge/docker-compose.yaml, tests/scaffoldings/repo_merge/setup-devel.yaml
On some of our build systems (2/3) we seem to hit this issue:
https://github.com/docker/for-linux/issues/388
With this merge request:
* The number of needed `chown` and `chmod` operations is greatly reduced so we can finish our CI Tests on those systems within the timeout (1h)
* autoaggregate now checks out files as odoo user right away (with the correct umask as default)
* python pre compile in /opt/odoo/custom/src is now performed as odoo user to reduce the need of chowning the python cache after compilation
* /opt/odoo/custom/src now belongs to odoo:odoo instead of root:odoo (this seemed to be more correct for development where odoos UID and GID are mapped to the developers UID and GID)
=> Improve build performance

15.0.Dockerfile
In Odoo 15.0, support for flanker has been included.
See https://github.com/odoo/odoo/blob/a7f7233e0eae8ee101d745a9813cba930fd03dcb/addons/mail/tools/mail_validation.py#L11-L27
Without this, we get these logs:
odoo.addons.mail.tools.mail_validation: The `flanker` Python module is not installed,so email validation fallback to email_normalize. Use 'pip install flanker' to install it
@moduon MT-221
=> [IMP] add missing flanker soft dependency

15.0.Dockerfile
As seen in https://github.com/mailgun/flanker/pull/164, for using flanker for validation, one needs additional dependencies.
That's Odoo's use case, so without this patch it fails with:
```
2022-02-02 12:26:32,758 29 WARNING odoo odoo.modules.loading: Module crm demo data failed to install, installed without demo data
Traceback (most recent call last):
File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 680, in _tag_root
f(rec)
File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 333, in _tag_function
_eval_xml(self, rec, env)
File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 204, in _eval_xml
return odoo.api.call_kw(model, method_name, args, kwargs)
File "/opt/odoo/custom/src/odoo/odoo/api.py", line 464, in call_kw
result = _call_kw_multi(method, model, args, …
```
=> [FIX] missing flanker dependencies

14.0.Dockerfile, 15.0.Dockerfile
This is one Odoo lazy dependency since v14.
https://github.com/odoo/odoo/blob/d4de2cfe64f42a711816bfbbc88a371519eee9da/addons/l10n_es_edi_sii/__manifest__.py#L46
@moduon MT-282
=> feat: add pyOpenSSL by default

15.0.Dockerfile
=> [IMP] 15.0: generate flanker cached tables during build

bin/preparedb
This script is called when using `invoke preparedb` in develop mode.
If developing enterprise code, this avoids an unnecessary warning.
=> feat: update db expiration date when preparing db

11.0.Dockerfile, 12.0.Dockerfile
filter=blob:none is not compatible with older git version in debian stretch
After git-aggregator 3.0.0 got relased our nightly CI builds failed for 11.0 and 12.0 with:
```
(ERROR) [21:20:47] git_aggregator.repo  misc-addons   /opt/odoo/custom/src/misc-addons> error calling ('git', 'clone', '--filter=blob:none', '--depth', '1', 'https://github.com/itpp-labs/misc-addons.git', '/opt/odoo/custom/src/misc-addons')
error: unknown option `filter=blob:none'
```
Info @wt-io-it
=> [FIX] git-aggregator: use git-aggregator < 3.0.0 for V11.0 and V12.0

11.0.Dockerfile, 12.0.Dockerfile
Reverts Tecnativa/doodba#523
It shouldn't be needed with latest git-aggregator version (3.0.1).
=> Revert "[FIX] git-aggregator: use git-aggregator < 3.0.0 for V11.0 and V12.0"

11.0.Dockerfile, 12.0.Dockerfile
https://www.postgresql.org/message-id/Y2kmqL%2BpCuSZiQBV%40msg.df7cb.de
Postgres no longer maintains debian stretch on their apt repos and moved the old packages to apt-archive.
On our CI this failed with the following error before the fix:
```
W: The repository 'http://apt.postgresql.org/pub/repos/apt stretch-pgdg Release' does not have a Release file.
E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/main/binary-amd64/Packages  404  Not Found [IP: 147.75.85.69 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
info @wt-io-it
=> [FIX] stretch: use apt-archive for postgres in stretch

15.0.Dockerfile, 16.0.Dockerfile, tests/__init__.py
The 16.0 Dockerfile is referencing an older fork of click-odoo-contrib, resulting in click-odoo-update not actually being functional out of the box on a 16.0 install, throwing the following error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/click_odoo/env_options.py", line 191, in _invoke
with self.environment_manager(
File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
return next(self.gen)
File "/usr/local/lib/python3.8/site-packages/click_odoo_contrib/update.py", line 277, in OdooEnvironmentWithUpdate
ignore_addons.update(core_addons[odoo.release.series])
KeyError: '16.0'
Error: '16.0'
```
Plus 16.0 requires a newer version anyway due to https://github.com/acsone/click-odoo-contrib/pull/119
Reading …
=> [FIX][16.0] click-odoo-contrib so out of date it doesnt understand 16.0

11.0.Dockerfile, 12.0.Dockerfile
Fix building images with debian stretch. Depending on the selected mirror we saw more and more issues with building the stretch images.
```
#6 1.419 Reading package lists...
#6 1.437 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#6 1.437 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#6 1.437 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#6 1.437 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found
#6 1.437 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
#6 1.437 E: Failed to fetch …
```
=> [FIX] 1[12].0: use archive for debian stretch packages

.github/workflows/ci.yaml, 11.0.Dockerfile
to avoid "execjs requires Ruby version >= 2.5.0." errors.
execjs seens to have a new tag 2.9.1 that fails installing as a dependency of autoprefixer-rails on our CI with the following error:
```
...
#14 [base  5/18] RUN gem install --no-rdoc --no-ri --no-update-sources autoprefixer-rails --version '<9.8.6'     && gem install --no-rdoc --no-ri --no-update-sources bootstrap-sass --version '<3.4'     && rm -Rf ~/.gem /var/lib/gems/*/cache/
#14 55.10 ERROR:  Error installing autoprefixer-rails:
#14 55.10 	execjs requires Ruby version >= 2.5.0.
#14 ERROR: executor failed running [/bin/sh -c gem install --no-rdoc --no-ri --no-update-sources autoprefixer-rails --version '<9.8.6'     && gem install --no-rdoc --no-ri --no-update-sources bootstrap-sass --version '<3.4'     && rm -Rf ~/.gem …
```
=> [FIX] 11.0: use execjs <2.9.1

.github/workflows/ci.yaml
actions is not working because running over Ubuntu-latest with Python 3.11
I tested on Py 3.10 and same error, but into PY 3.9 is working
=> [IMP] use PY 3.9 for avoid issue at install poetry

.github/workflows/ci.yaml, 17.0.Dockerfile, tests/__init__.py
- Dockerfile copied from 16.0 and slightly adapted
- Fix tests
- Make it `:latest`.
- Deprecate some old Odoo versions.
- Bump PG to 15
- Switch to Python 3.10
- Adapted CI
@Tecnativa TT45808
=> Add Odoo 17.0

16.0.Dockerfile, tests/__init__.py
Due to this fixes (https://github.com/Tecnativa/doodba/pull/575), we can now use python 3.10 in v16.0.
CC @Tecnativa TT45957
=> [IMP] Use python 3.10 in v16.0

16.0.Dockerfile, 17.0.Dockerfile
The newest flanker version includes 2 dependencies that are not automatically installed, so we need to explicitly add them.
@Tecnativa
=> [FIX] flanker new version dependencies

16.0.Dockerfile, 17.0.Dockerfile, tests/__init__.py
I've run out of time to investigate further, but somehow a `/root/.ssh` directory is being prematurely created. This results in the symlink to /opt/odoo/custom/ssh being created as sub-directory (i.e. /root/.ssh/ssh rather than /root/.ssh).
I hope this change is suitable? 
I've tried to add a quick test to ensure that this is perhaps caught in future. I have not backported this to previous versions as it does not seem to be occurring there.
---
In the interim, if anyone wants a temporary workaround (created as `odoo/custom/build.d/099-fix-aggregate`):
```
#!/bin/bash
set -e
if [ -e ~root/.ssh/ssh/ ]; then
log WARNING "Found nested SSH directory. Performing workaround for temporary fix for #582 / #585"
unlink ~root/.ssh/ssh
rm -rf ~root/.ssh/
ln -sf /opt/odoo/custom/ssh ~root/.ssh
sync
fi …
```
=> [FIX] if ~root/.ssh/ is prematurely created, we need to remove it, ensuring that AUTOAGGREGATE can read the ssh/config correctly

16.0.Dockerfile, 17.0.Dockerfile, tests/__init__.py, tests/scaffoldings/uids_998/Dockerfile, tests/scaffoldings/uids_998/docker-compose.yaml
This is a fix for #586
With debian bookworm images it was not possible to run doodba with UID/GID 998 because these id's where used by systemd-network user.
This PR configures the system user boundary for debian to 499 / 500 (which is / was used by macOS for its users) and ensures that systemd-network user uses UID/GID=499
Previously UID 998 was only tested on our CI systems implicitly by the geoip tests (which were never activated on this projects CI), so now there is also a test that explicitly makes sure this use case (testing doodba with gitlab-runner) works.
Info @wt-io-it
=> Master fix uids GitHub

16.0.Dockerfile, 17.0.Dockerfile
Hello, 
I found that the symlink to /opt/odoo/custom/ssh still being created as sub-directory (/root/.ssh/ssh) so I got an error when I tried to  build my Odoo image.
Docker uses "/bin/sh" as default shell and "[[ ]]" is a specific comparison construct of Bash.
I remove the brackets and now the symlinks to /opt/odoo/custom/ssh is being created succesfully.
Issue origin: https://github.com/Tecnativa/doodba/pull/585
@pedrobaeza
=> [FIX] 16/17: Proper ~root/.ssh pre-removal

.github/workflows/ci.yaml
Hi @pedrobaeza small fix incoming:
1. The tags which are pushed should now be as before - {ODOO_VERSION}, {ODOO_VERSION}-onbuild and latest, latest-onbuild (where applicable)
2. The push to ghcr.io failed with the default credentials, I have switched them to the old ones hoping they will pass this time. If this also fails maybe you need to look into the permissions of the default github.repository_owner / secrets.GITHUB_TOKEN since authentication was sucessful.
Also after this works you would need to delete the extra {ODOO_VERSION}onbuild (with the missing -)
Fingers crossed :crossed_fingers:
=> [FIX] Fix docker image tags and ghcr.io auth credentials

13.0.Dockerfile, 14.0.Dockerfile, tests/scaffoldings/repo_merge/custom/build.d/099-create-fake-odoo
Fixing issue mentioned here https://github.com/Tecnativa/doodba/pull/623#issuecomment-2378896167
=> [FIX] Mark /tmp/fake-odoo as safe

entrypoint.d/20-postgres-wait
When having to connect to external database access, you often only have access to a specific user/password on a single database, with no rights to access 'postgres' database, and thus no rights to list databases. (Using: `REVOKE ALL ON DATABASE postgres FROM PUBLIC;`, which is a common security practice). Notice that OVH for instance seems to do that on their [mutualized postgres offers](https://www.ovhcloud.com/en/public-cloud/postgresql/)
If odoo itself has known [issues](https://github.com/odoo/odoo/issues/12850) into supporting this scenario, it is easily patchable (cf: https://github.com/odoo/odoo/issues/12850#issuecomment-2222886101 ).
If you can't list databases, you probably have the `$PGDATABASE` set, so I triggered the change on the existence of this variable. Although, I'm not …
=> [FIX] 20-postgres-wait: avoid assuming you have permission to list database

.github/workflows/ci.yaml, .vscode/settings.json, 18.0.Dockerfile, tests/__init__.py
=> [ADD] Odoo 18.0

.github/workflows/ci.yaml
=> [FIX] Not testing Doodba 18.0 to be able to push image

16.0.Dockerfile, 17.0.Dockerfile, 18.0.Dockerfile
pip install gevent==21.8.0 fails with exception when installing with pip in ubuntu/debian. gevent 22.10.2 then also requires greenlet 2.0.2
`docker run --rm -it python:3.10-bookworm bash -c 'pip install gevent==21.8.0'` fails with
```
Collecting gevent==21.8.0
Downloading gevent-21.8.0.tar.gz (6.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 46.4 MB/s eta 0:00:00
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [45 lines of output]
Compiling src/gevent/resolver/cares.pyx because it changed.
[1/1] Cythonizing src/gevent/resolver/cares.pyx
performance hint: src/gevent/libev/corecext.pyx:1325:0: Exception check on '_syserr_cb' …
```
=> [IMP] 16,17,18: use gevent 22.10.2

15.0.Dockerfile
```Dockerfile
RUN apt-get purge -yqq $build_deps \
&& apt-get autopurge -yqq \
&& rm -Rf /var/lib/apt/lists/* /tmp/*
```
Does not make sense from docker layer perspective if it's not run in the same layer as the install. It also does not make sense from a shell perspective if `$build_deps` is not set for `apt-get purge -yqq $build_deps`.
With https://github.com/Tecnativa/doodba/commit/21b8bde780564d92b150e72a22b2ada90c95d65e#diff-32129c0c5001d86cef22a1cecd12993dd630e851a67b5d286cef38b2399ac96bR170-R173 it seems build_deps are no longer removed after components are built and installed.
If this behaviour is required in TT54577 (it's always hard to assume what the issues are you are experiencing if the description is pretty empty: https://github.com/Tecnativa/doodba/pull/644) do not merge …
=> [FIX] 15.0: purge apt data in the same layer as install

14.0.Dockerfile, 15.0.Dockerfile
Fixed incompatibility error between gevent and greenlet:
`ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject`
To ensure consistency and compatibility across architectures, we now set `gevent==21.12.0` and `greenlet==1.1.0` for both amd64 and arm64. This prevents binary mismatch issues and improves container stability.
CC @Tecnativa TT55390
=> [IMP] Set gevent==21.12.0 & greenlet==1.1.0 for all architectures to ensure consistency

16.0.Dockerfile, 17.0.Dockerfile, 18.0.Dockerfile
I noticed yesterday that dockerhub started rolling out updated images for alpine / python, when one of our builds broke when using `python:3.11-alpine` `pip install .` gave an error `error: invalid command 'bdist_wheel'`. Upgrading setuptools fixes this.
I assume this is with regards to CVE-2024-6345 but cannot find out anything more why that may break pip install. The installed (numerical) version of setuptools stayed the same but maybe there is a strange patch in there.
Today our doodba (and docker-whitelist) builds broke in the morning for 16.0, 17.0 and 18.0:
```
...
#25 53.04   Building wheel for qrcode (setup.py): started
#25 53.22   Building wheel for qrcode (setup.py): finished with status 'error'
#25 53.23   error: subprocess-exited-with-error
#25 53.23   
#25 53.23   × python …
```
=> [FIX] build: need to upgrade setuptools

poetry.lock, pyproject.toml, tests/__init__.py
Without these changes, the ‘onbuild’ docker hub image is used when launching the tests: https://hub.docker.com/r/tecnativa/doodba/tags
I consider this a bug. We are interested in testing the latest changes and testing the new changes on the new image, not on the last one that managed to be released. I see it as a mismatch between what I think I'm testing and what I'm actually testing.... and it can happen as now, that a problem is not detected when changes are made but when merging and launching new tests.
=> [FIX] Test Environment: Don't use published 'onbuild' image

.github/workflows/ci.yaml
Build & push Docker images in PRs before running tests, introducing build-push-pr → test-pr so tests (and local dev) use the freshly built tags.
Official images remain published only from master after tests succeed.
=> [IMP] Using test images on test-pr stage

16.0.Dockerfile, 17.0.Dockerfile, 18.0.Dockerfile
with https://github.com/Tecnativa/doodba/pull/578 the images for 16.0 and 17.0 were changed to use 2 layers instead of one layer.
We could also keep the 2 layers starting with 16.0, but then i would suggest we check the cleanup and sync code at the end if it's not needed anymore or if it's needed twice.
```bash
&& apt-get autopurge -yqq \
&& rm -Rf wkhtmltox.deb /var/lib/apt/lists/* /tmp/* \
&& sync
```
Info @wt-io-it
=> [FIX][16.0][17.0][18.0] Dockerfile: restore single layer install
